source_data_dir: '/data/SBC_MFCC_NORM_1_13/'
target_data_dir: '/data/GP_MFCC_NORM_1_13/'
source_speech_metadata: '/home/gnani/LID_DA/source_600.csv'
target_speech_metadata: '/home/gnani/LID_DA/target_600.csv'
source_cmvn: '/home/gnani/LID_DA/train/cmvn.ark'
target_cmvn: '/home/gnani/LID_DA/trell_train/cmvn.ark'
model_state_file: 'first_model'
model_save_dir: 'test2/'
source_language_set: 'bengali english hindi kannada malayalam marathi tamil telugu'
target_language_set: 'hindi'
seed: 1337
input_signal_params:
    feature_type: 'MFCC'
    experiment_type: 'domain_sbc2gp'
    max_num_frames: 384
    num_frames: 300
    sampling_rate: 16000
    sample_segment: True
    start_index: 0
    end_index: 40
model_arch:
    nn_model: ConvNet_DA
    feature_dim: 40
    num_classes: 8
    bottleneck: True
    bottleneck_size: 512
    output_dim: 512
    frame_dropout: True
    feature_dropout: False
    signal_dropout_prob: 0.0
    num_channels:
       - 128
       - 256
       - 512
    filter_sizes:
       - 5
       - 10
       - 10
    stride_steps:
       - 1
       - 1
       - 1
    pooling_type: 'max'
training_hyperparams:
    learning_rate: 0.001
    batch_size: 256
    num_epochs: 100
    early_stopping_criteria: 50
cuda: True
catch_keyboard_interrupt: True
reload_from_files: False
expand_filepaths_to_save_dir: True

